# Generated by Django 4.2.9 on 2024-04-13 06:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutOurAlumniNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                (
                    "highlight_word",
                    models.CharField(blank=True, default="", max_length=120, null=True),
                ),
                ("description", models.TextField()),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="alumni/about_our/image/", verbose_name="Image"
                    ),
                ),
            ],
            options={
                "verbose_name": "About Our Alumni Network",
                "verbose_name_plural": "About Our Alumni Networks",
                "db_table": "alumni_about_our_alumni_network",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="AlumniActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("sub_title", models.CharField(max_length=250)),
                ("description", models.TextField()),
                ("date", models.DateField(default=datetime.date.today)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Alumni Activity",
                "verbose_name_plural": "Alumni Activities",
                "db_table": "alumni_alumni_activity",
                "ordering": ("-date",),
            },
        ),
        migrations.CreateModel(
            name="AlumniSpotlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("sub_title", models.CharField(max_length=220)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="alumni/spotlight/image/", verbose_name="Image"
                    ),
                ),
            ],
            options={
                "verbose_name": "Alumni Spotlight",
                "verbose_name_plural": "Alumni Spotlights",
                "db_table": "alumni_alumni_spotlight",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="AlumniTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("designation", models.CharField(max_length=220)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="alumni/team/images/", verbose_name="Image"
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Alumni Team",
                "verbose_name_plural": "Alumni Teams",
                "db_table": "alumni_alumni_team",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="BEdSubjectChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
            ],
            options={
                "verbose_name": "B.Ed Subject Choice",
                "verbose_name_plural": "B.Ed Subject Choices",
                "db_table": "alumni_b_ed_subject_choice",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="EducationalStatusChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
            ],
            options={
                "verbose_name": "Educational Status Choice",
                "verbose_name_plural": "Educational Status Choices",
                "db_table": "alumni_educational_status_choice",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="alumni/faculty/images/", verbose_name="Image"
                    ),
                ),
                ("designation", models.CharField(max_length=120)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Faculty",
                "verbose_name_plural": "Faculties",
                "db_table": "alumni_faculty",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="GenderChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
            ],
            options={
                "verbose_name": "Gender Choice",
                "verbose_name_plural": "Gender Choices",
                "db_table": "alumni_gender_choice",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="MaritalStatusChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
            ],
            options={
                "verbose_name": "Marital Status Choice",
                "verbose_name_plural": "Marital Status Choices",
                "db_table": "alumni_marital_status_choice",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("batch", models.CharField(max_length=120)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
                "db_table": "alumni_student",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="YearOfStudyChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
            ],
            options={
                "verbose_name": "Year of Study Choice",
                "verbose_name_plural": "Year of Study Choices",
                "db_table": "alumni_year_of_study_choice",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="AlumniNetworkRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=25)),
                ("last_name", models.CharField(max_length=30)),
                ("phone_number", models.CharField(max_length=10, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("address", models.TextField()),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True,
                        null=True,
                        upload_to="alumni/registration/image/",
                        verbose_name="Image",
                    ),
                ),
                ("jntc_period", models.TextField(blank=True, null=True)),
                ("suggestion", models.TextField(blank=True, null=True)),
                ("date", models.DateField(default=datetime.date.today)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "b_ed_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="alumni.bedsubjectchoice",
                    ),
                ),
                (
                    "educational_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="alumni.educationalstatuschoice",
                    ),
                ),
                (
                    "gender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="alumni.genderchoice",
                    ),
                ),
                (
                    "marital_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="alumni.maritalstatuschoice",
                    ),
                ),
                (
                    "year_of_study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="alumni.yearofstudychoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alumni Network Registration",
                "verbose_name_plural": "Alumni Network Registrations",
                "db_table": "alumni_alumni_network_registration",
                "ordering": ("-date",),
            },
        ),
        migrations.CreateModel(
            name="ActivityGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="alumni/activities/image/", verbose_name="Image"
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="alumni.alumniactivity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Gallery",
                "verbose_name_plural": "Activity Galleries",
                "db_table": "alumni_activity_gallery",
                "ordering": ("id",),
            },
        ),
    ]
