# Generated by Django 4.2.9 on 2024-04-13 06:32

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BEdExaminationResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("date", models.DateField(default=datetime.date.today)),
            ],
            options={
                "verbose_name": "B.Ed Examination Result",
                "verbose_name_plural": "B.Ed Examination Results",
                "db_table": "student_zone_bed_examination_result",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="BEdResultStatusBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch", models.CharField(max_length=120)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "B.Ed Result Status Batch",
                "verbose_name_plural": "B.Ed Result Status Batchs",
                "db_table": "student_zone_bed_result_status_batch",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="DownloadFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        default="",
                        upload_to="student_zone/downloads/files/images",
                        verbose_name="Image",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="student_zone/downloads/files",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "jpg"]
                            )
                        ],
                    ),
                ),
                ("date", models.DateField(default=datetime.date.today)),
            ],
            options={
                "verbose_name": "Download File",
                "verbose_name_plural": "Download Files",
                "db_table": "student_zone_download_file",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="DownloadSpotlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("sub_title", models.CharField(max_length=220)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="student_zone/downloads/image/", verbose_name="Image"
                    ),
                ),
            ],
            options={
                "verbose_name": "Download Spotlight",
                "verbose_name_plural": "Download Spotlights",
                "db_table": "student_zone_download_spotlight",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="MagazineFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        default="",
                        upload_to="student_zone/magazines/files/images",
                        verbose_name="Image",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="student_zone/magazines/files",
                        validators=[
                            django.core.validators.FileExtensionValidator(["pdf"])
                        ],
                    ),
                ),
                ("date", models.DateField(default=datetime.date.today)),
            ],
            options={
                "verbose_name": "Magazine File",
                "verbose_name_plural": "Magazine Files",
                "db_table": "student_zone_magazine_file",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="BEdStudent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "register_number",
                    models.CharField(
                        max_length=21,
                        validators=[django.core.validators.RegexValidator("^[0-9]+$")],
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("date_of_birth", models.DateField(default=datetime.date.today)),
                (
                    "file",
                    models.FileField(
                        upload_to="student_zone/b_ed_students/results/files",
                        validators=[
                            django.core.validators.FileExtensionValidator(["pdf"])
                        ],
                    ),
                ),
                (
                    "results",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="student_zone.bedexaminationresult",
                    ),
                ),
            ],
            options={
                "verbose_name": "B.Ed Student",
                "verbose_name_plural": "B.Ed Students",
                "db_table": "student_zone_bed_student",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="BEdResultStatusBatchYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=120)),
                (
                    "file",
                    models.FileField(
                        upload_to="student_zone/bed_result_status/files",
                        validators=[
                            django.core.validators.FileExtensionValidator(["pdf"])
                        ],
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="years",
                        to="student_zone.bedresultstatusbatch",
                    ),
                ),
            ],
            options={
                "verbose_name": "B.Ed Result Status Batch Year",
                "verbose_name_plural": "B.Ed Result Status Batch Years",
                "db_table": "student_zone_bed_result_status_batch_year",
            },
        ),
        migrations.CreateModel(
            name="BEdResultStatusBatchSemester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester", models.CharField(max_length=120)),
                (
                    "file",
                    models.FileField(
                        upload_to="student_zone/bed_result_status/files",
                        validators=[
                            django.core.validators.FileExtensionValidator(["pdf"])
                        ],
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semesters",
                        to="student_zone.bedresultstatusbatch",
                    ),
                ),
            ],
            options={
                "verbose_name": "B.Ed Result Status Batch Semester",
                "verbose_name_plural": "B.Ed Result Status Batch Semesters",
                "db_table": "student_zone_bed_result_status_batch_semester",
            },
        ),
    ]
