# Generated by Django 4.2.9 on 2024-04-13 06:32

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactUsDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField()),
                (
                    "map_link",
                    models.URLField(blank=True, default="", max_length=290, null=True),
                ),
                ("phone_number", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
            ],
            options={
                "verbose_name": "ContactUs Detail",
                "verbose_name_plural": "ContactUs Details",
                "db_table": "contact_contact_us_detail",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="ContactUsEnquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=25)),
                ("last_name", models.CharField(max_length=30)),
                ("phone_number", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField(max_length=250)),
            ],
            options={
                "verbose_name": "ContactUs Enquiry",
                "verbose_name_plural": "ContactUs Enquiries",
                "db_table": "contact_contact_us_enquiry",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="ContactUsSpotlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("sub_title", models.CharField(max_length=150)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="contact_us/spotlight/image/", verbose_name="Image"
                    ),
                ),
            ],
            options={
                "verbose_name": "ContactUs Spotlight",
                "verbose_name_plural": "ContactUs Spotlights",
                "db_table": "contact_contact_us_spotlight",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="JNTCLogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="logo/image/", verbose_name="Image"
                    ),
                ),
            ],
            options={
                "verbose_name": "JNTC Logo",
                "verbose_name_plural": "JNTC Logo",
                "db_table": "contact_jntc_logo",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "icon",
                    models.FileField(
                        default="image.svg", upload_to="contact_us/social_media/icons/"
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Media",
                "verbose_name_plural": "Social Media",
                "db_table": "contact_social_media",
                "ordering": ("id",),
            },
        ),
    ]
