# Generated by Django 4.2.9 on 2024-04-13 06:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomeAbout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="home/about/images/", verbose_name="Image"
                    ),
                ),
            ],
            options={
                "verbose_name": "Home About",
                "verbose_name_plural": "Home Abouts",
                "db_table": "web_home_About",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="HomeAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("link", models.URLField(blank=True, null=True)),
                ("date", models.DateField(default=datetime.date.today)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Home Announcement",
                "verbose_name_plural": "Home Announcements",
                "db_table": "web_home_announcement",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="HomeInstitutionHeading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name": "Home Institution Heading",
                "verbose_name_plural": "Home Institution Headings",
                "db_table": "web_home_institution_heading",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="HomeLatestNews",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("sub_title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("date", models.DateField(default=datetime.date.today)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Home Latest News",
                "verbose_name_plural": "Home Latest News",
                "db_table": "web_home_latest_news",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="HomeNewsAndEventsSpotlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("sub_title", models.CharField(max_length=255)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="home/news_and_events/spotlight/image/",
                        verbose_name="Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Home News and Events Spotlight",
                "verbose_name_plural": "Home News and Events Spotlights",
                "db_table": "web_home_news_and_events_spotlight",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="HomeSpotlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("sub_title", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Home Spotlight",
                "verbose_name_plural": "Home Spotlights",
                "db_table": "web_home_spotlight",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="HomeUpcomingEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("sub_title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("date", models.DateField(default=datetime.date.today)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Home Upcoming Event",
                "verbose_name_plural": "Home Upcoming Events",
                "db_table": "web_home_upcoming_event",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="HomeUpcomingEventGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="home/news_and_events/events/images/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "events",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="web.homeupcomingevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Home Upcoming Event Gallery",
                "verbose_name_plural": "Home Upcoming Event Galleries",
                "db_table": "web_home_Upcoming_Event__gallery",
            },
        ),
        migrations.CreateModel(
            name="HomeSpotlightGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="home/spotlight/images/", verbose_name="Image"
                    ),
                ),
                (
                    "spotlight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="web.homespotlight",
                    ),
                ),
            ],
            options={
                "verbose_name": "Home Spotlight Gallery",
                "verbose_name_plural": "Home Spotlight Galleries",
                "db_table": "web_home_spotlight_gallery",
            },
        ),
        migrations.CreateModel(
            name="HomeLatestNewsGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="home/news_and_events/latest_news/images/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="web.homelatestnews",
                    ),
                ),
            ],
            options={
                "verbose_name": "Home Latest News Gallery",
                "verbose_name_plural": "Home Latest News Galleries",
                "db_table": "web_home_latest_news__gallery",
            },
        ),
        migrations.CreateModel(
            name="HomeInstitution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="home/institution/images/", verbose_name="Image"
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "institution",
                    models.ForeignKey(
                        default="1",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="institution",
                        to="web.homeinstitutionheading",
                    ),
                ),
            ],
            options={
                "verbose_name": "Home Institution",
                "verbose_name_plural": "Home Institutions",
                "db_table": "web_home_institution",
                "ordering": ("-id",),
            },
        ),
    ]
