# Generated by Django 4.2.9 on 2024-04-13 06:32

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicCalenderBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch", models.CharField(max_length=220)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Academic Calender Batch",
                "verbose_name_plural": "Academic Calender Batchs",
                "db_table": "academic_academic_calender_batch",
                "ordering": ("-batch",),
            },
        ),
        migrations.CreateModel(
            name="AcademicCalenderSpotlight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("sub_title", models.CharField(max_length=220)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="academic/academic_calender/spotlight/image/",
                        verbose_name="Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Academic Calender Spotlight",
                "verbose_name_plural": "Academic Calender Spotlights",
                "db_table": "academic_academic_calender_spotlight",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="AcademicCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("arrow_tag", models.CharField(default="", max_length=255)),
                ("description", models.TextField()),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="academic/Course/images/", verbose_name="Image"
                    ),
                ),
                ("date", models.DateField(default=datetime.date.today)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Academics Course",
                "verbose_name_plural": "Academics Courses",
                "db_table": "academic_academic_course",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="AcademicCourseHeading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("sub_title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Academic Course Heading",
                "verbose_name_plural": "Academic Course Headings",
                "db_table": "academic_academic_course_heading",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="AccountFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        default="",
                        upload_to="academic/account/files/images/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="academic/account/files",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "jpg"]
                            )
                        ],
                    ),
                ),
                ("date", models.DateField(default=datetime.date.today)),
            ],
            options={
                "verbose_name": "Account File",
                "verbose_name_plural": "Account Files",
                "db_table": "academic_account_file",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="AccountSpotlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("sub_title", models.CharField(max_length=220)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="academic/account/spotlight/image/",
                        verbose_name="Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Account Spotlight",
                "verbose_name_plural": "Account Spotlights",
                "db_table": "academic_account_spotlight",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="EvaluationPolicyFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        default="",
                        upload_to="academic/evaluation_policy/files/images/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="academic/evaluation_policy/files",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "jpg"]
                            )
                        ],
                    ),
                ),
                ("date", models.DateField(default=datetime.date.today)),
            ],
            options={
                "verbose_name": "Evaluation Policy File",
                "verbose_name_plural": "Evaluation Policy Files",
                "db_table": "academic_evaluation_policy_file",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="EvaluationPolicySpotlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("sub_title", models.CharField(max_length=220)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="academic/evaluation_policy/spotlight/image/",
                        verbose_name="Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evaluation Policy Spotlight",
                "verbose_name_plural": "Evaluation Policy Spotlights",
                "db_table": "academic_evaluation_policy_spotlight",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="ProgramAbout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(blank=True, max_length=120, null=True)),
                ("title", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "highlight_word",
                    models.CharField(blank=True, default="", max_length=120, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Academic Programmes About",
                "verbose_name_plural": "Academic Programmes Abouts",
                "db_table": "academic_program_About",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="ProgramObjective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(blank=True, max_length=120, null=True)),
                ("title", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "highlight_word",
                    models.CharField(blank=True, default="", max_length=120, null=True),
                ),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True,
                        null=True,
                        upload_to="academic/programmes/objectives/image/",
                        verbose_name="Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Academic Programmes Objective",
                "verbose_name_plural": "Academic Programmes Objectives",
                "db_table": "academic_program_objective",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="ProgramSpotlight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tag", models.CharField(blank=True, max_length=120, null=True)),
                ("title", models.CharField(blank=True, max_length=120, null=True)),
                ("sub_title", models.CharField(blank=True, max_length=220, null=True)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True,
                        null=True,
                        upload_to="academic/programmes/spotlight/image/",
                        verbose_name="Image",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("date", models.DateField(default=datetime.date.today)),
            ],
            options={
                "verbose_name": "Academic Programme",
                "verbose_name_plural": "Academic Programmes",
                "db_table": "academic_program_spotlight",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="ProgramObjectivePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=225, null=True)),
                (
                    "objective",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point",
                        to="academic.programobjective",
                    ),
                ),
            ],
            options={
                "verbose_name": "Academic Programmes Objective Point",
                "verbose_name_plural": "Academic Programmes Objective Points",
                "db_table": "academic_program_objective_point",
                "ordering": ("-id",),
            },
        ),
        migrations.AddField(
            model_name="programobjective",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="objective",
                to="academic.programspotlight",
            ),
        ),
        migrations.CreateModel(
            name="ProgramInformationFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(blank=True, max_length=120, null=True)),
                ("title", models.CharField(blank=True, max_length=120, null=True)),
                ("sub_title", models.CharField(blank=True, max_length=220, null=True)),
                (
                    "file_name",
                    models.CharField(blank=True, default="", max_length=220, null=True),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="academic/programmes/Information/files/",
                        validators=[
                            django.core.validators.FileExtensionValidator(["pdf"])
                        ],
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data",
                        to="academic.programspotlight",
                    ),
                ),
            ],
            options={
                "verbose_name": "Academic Programmes Information File",
                "verbose_name_plural": "Academic Programmes Information Files",
                "db_table": "academic_program_information_file",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="ProgramInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(blank=True, max_length=120, null=True)),
                ("title", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "highlight_word",
                    models.CharField(blank=True, default="", max_length=120, null=True),
                ),
                ("sub_title", models.CharField(blank=True, max_length=220, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True,
                        null=True,
                        upload_to="academic/programmes/Information/image/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="information",
                        to="academic.programspotlight",
                    ),
                ),
            ],
            options={
                "verbose_name": "Academic Programmes Information",
                "verbose_name_plural": "Academic Programmes Informations",
                "db_table": "academic_program_information",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="ProgramGatewayHeading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(blank=True, max_length=120, null=True)),
                ("title", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gateway",
                        to="academic.programspotlight",
                    ),
                ),
            ],
            options={
                "verbose_name": "Academic Programmes Gateway Heading",
                "verbose_name_plural": "Academic Programmes Gateway Heading",
                "db_table": "academic_program_gateway_heading",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="ProgramGateway",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tag", models.CharField(blank=True, max_length=120, null=True)),
                ("title", models.CharField(blank=True, max_length=120, null=True)),
                ("sub_title", models.CharField(blank=True, max_length=220, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True,
                        null=True,
                        upload_to="academic/programmes/gateway/image/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "object",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="object",
                        to="academic.programgatewayheading",
                    ),
                ),
            ],
            options={
                "verbose_name": "Academic Programmes Gateway",
                "verbose_name_plural": "Academic Programmes Gateways",
                "db_table": "academic_program_gateway",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="ProgramAboutGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True,
                        null=True,
                        upload_to="academic/programmes/about/images/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "about",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="academic.programabout",
                    ),
                ),
            ],
            options={
                "verbose_name": "Academic Programmes About gallery",
                "verbose_name_plural": "Academic Programmes About galleries",
                "db_table": "academic_program_about_gallery",
                "ordering": ("-id",),
            },
        ),
        migrations.AddField(
            model_name="programabout",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="about",
                to="academic.programspotlight",
            ),
        ),
        migrations.CreateModel(
            name="AcademicCalenderBatchYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=120)),
                (
                    "file",
                    models.FileField(
                        upload_to="academic/academic_calender/files",
                        validators=[
                            django.core.validators.FileExtensionValidator(["pdf"])
                        ],
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="years",
                        to="academic.academiccalenderbatch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Academic Calender Batch Year",
                "verbose_name_plural": "Academic Calender Batch Years",
                "db_table": "academic_academic_calender_batch_year",
            },
        ),
        migrations.CreateModel(
            name="AcademicCalenderBatchSemester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester", models.CharField(max_length=120)),
                (
                    "file",
                    models.FileField(
                        upload_to="academic/academic_calender/files",
                        validators=[
                            django.core.validators.FileExtensionValidator(["pdf"])
                        ],
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semesters",
                        to="academic.academiccalenderbatch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Academic Calender Batch Semester",
                "verbose_name_plural": "Academic Calender Batch Semesters",
                "db_table": "academic_academic_calender_batch_semester",
            },
        ),
    ]
