# Generated by Django 4.2.9 on 2024-04-13 06:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alumni", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IQACAbout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                (
                    "highlight_word",
                    models.CharField(blank=True, default="", max_length=120, null=True),
                ),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name": "IQAC About",
                "verbose_name_plural": "IQAC Abouts",
                "db_table": "iqac_iqac_about",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="IQACFunctionName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "IQAC Function Name",
                "verbose_name_plural": "IQAC Function Names",
                "db_table": "iqac_iqac_function_name",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="IQACSpotlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("sub_title", models.CharField(max_length=220)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="iqac/spotlight/image/", verbose_name="Image"
                    ),
                ),
            ],
            options={
                "verbose_name": "IQAC Spotlight",
                "verbose_name_plural": "IQAC Spotlights",
                "db_table": "iqac_iqac_spotlight",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="IQACTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=220)),
                ("designation", models.CharField(max_length=250)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="iqac/team/images/", verbose_name="Image"
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "IQAC Team",
                "verbose_name_plural": "IQAC Teams",
                "db_table": "iqac_iqac_team",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="LocalSociety",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("panchayat", models.CharField(max_length=220)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Local Society",
                "verbose_name_plural": "Local Societies",
                "db_table": "iqac_Local_Society",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="IQACOurVision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                (
                    "highlight_word",
                    models.CharField(blank=True, default="", max_length=120, null=True),
                ),
                ("description", models.TextField()),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vision",
                        to="iqac.iqacteam",
                    ),
                ),
            ],
            options={
                "verbose_name": "IQAC Our Vision",
                "verbose_name_plural": "IQAC Our Visions",
                "db_table": "iqac_iqac_our_vision",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="IQACObjective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                (
                    "highlight_word",
                    models.CharField(blank=True, default="", max_length=120, null=True),
                ),
                ("description", models.TextField()),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objective",
                        to="iqac.iqacteam",
                    ),
                ),
            ],
            options={
                "verbose_name": "IQAC Objective",
                "verbose_name_plural": "IQAC Objectives",
                "db_table": "iqac_iqac_objective",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="IQACFunctionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_of_event", models.CharField(max_length=55)),
                ("file", models.FileField(upload_to="iqac/function/files/")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event",
                        to="iqac.iqacfunctionname",
                    ),
                ),
            ],
            options={
                "verbose_name": "IQAC Function Record",
                "verbose_name_plural": "IQAC Function Records",
                "db_table": "iqac_iqac_function_record",
                "ordering": ("-year_of_event",),
            },
        ),
        migrations.CreateModel(
            name="IQACComplaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=datetime.datetime.now)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("complaint", models.TextField()),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subjects",
                        to="alumni.bedsubjectchoice",
                    ),
                ),
                (
                    "year_of_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="years",
                        to="alumni.yearofstudychoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "IQAC Complaint",
                "verbose_name_plural": "IQAC Complaints",
                "db_table": "iqac_iqac_complaint",
                "ordering": ("-year_of_batch",),
            },
        ),
        migrations.CreateModel(
            name="IQACAboutGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="iqac/about/image/", verbose_name="Image"
                    ),
                ),
                (
                    "about",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="iqac.iqacabout",
                    ),
                ),
            ],
            options={
                "verbose_name": "IQAC About Gallery",
                "verbose_name_plural": "IQAC About Galleries",
                "db_table": "iqac_iqac_about_gallery",
                "ordering": ("-id",),
            },
        ),
    ]
