# Generated by Django 4.2.9 on 2024-04-13 06:32

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutUsSpotlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("sub_title", models.CharField(max_length=255)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="about_us/spotlight/image/", verbose_name="Image"
                    ),
                ),
            ],
            options={
                "verbose_name": "AboutUs Spotlight",
                "verbose_name_plural": "AboutUs Spotlights",
                "db_table": "about_about_us_spotlight",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="AnnualReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_of_report", models.CharField(max_length=55)),
                ("file", models.FileField(upload_to="about_us/annual_report/files/")),
            ],
            options={
                "verbose_name": "Annual Report",
                "verbose_name_plural": "Annual Reports",
                "db_table": "about_annual_report",
                "ordering": ("-year_of_report",),
            },
        ),
        migrations.CreateModel(
            name="FutureGoalGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_title", models.CharField(max_length=150)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="about_us/future_goal_gallery/image/",
                        verbose_name="Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Future Goal Gallery",
                "verbose_name_plural": "Future Goal Galleries",
                "db_table": "about_future_goal_gallery",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("sub_title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="about_us/history/image/", verbose_name="Image"
                    ),
                ),
            ],
            options={
                "verbose_name": "History",
                "verbose_name_plural": "Histories",
                "db_table": "about_history",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="Objective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name": "Objective",
                "verbose_name_plural": "Objectives",
                "db_table": "about_objective",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="OurAdministrativeStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="about_us/administrative_staff/images/",
                        verbose_name="Image",
                    ),
                ),
                ("designation", models.CharField(max_length=120)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Our Administrative Staff",
                "verbose_name_plural": "Our Administrative Staffs",
                "db_table": "about_our_administrative_staff",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="OurManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="about_us/our_management/images/",
                        verbose_name="Image",
                    ),
                ),
                ("designation", models.CharField(max_length=120)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Our Management",
                "verbose_name_plural": "Our Managements",
                "db_table": "about_our_management",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="RulesAndRegulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                (
                    "file",
                    models.FileField(upload_to="about_us/rules_and_regulations/files/"),
                ),
            ],
            options={
                "verbose_name": "Rules And Regulation",
                "verbose_name_plural": "Rules And Regulations",
                "db_table": "about_rules_and_regulation",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="Planning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goal",
                        to="about.futuregoalgallery",
                    ),
                ),
            ],
            options={
                "verbose_name": "planning",
                "verbose_name_plural": "plannings",
                "db_table": "about_planning",
                "ordering": ("-id",),
            },
        ),
    ]
