# Generated by Django 5.0.4 on 2024-04-20 11:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0002_foundation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="foundation",
            options={
                "ordering": ("-id",),
                "verbose_name": "Foundation",
                "verbose_name_plural": "Foundations",
            },
        ),
    ]
