# Generated by Django 5.0.4 on 2024-04-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0003_alter_foundation_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foundation",
            name="sub_title",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
