# Generated by Django 5.0.4 on 2024-04-22 07:45

import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0006_ourofficestaff"),
    ]

    operations = [
        migrations.CreateModel(
            name="PtaCommitee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="about_us/pta_commitee/images/", verbose_name="Image"
                    ),
                ),
                ("designation", models.CharField(max_length=120)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Our Pta Commitee",
                "verbose_name_plural": "Our Pta Commitees",
                "db_table": "about_our_pta_commitee",
                "ordering": ("id",),
            },
        ),
    ]
