# Generated by Django 4.2.9 on 2024-04-13 06:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FacilityAdministrative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "highlight_title",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("sub_title", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Facility Administrative",
                "verbose_name_plural": "Facility Administratives",
                "db_table": "resources_facility_administrative",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="FacilityCollegeGround",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                (
                    "highlight_title",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("description", models.TextField()),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="resources/facility/college_ground/image/",
                        verbose_name="Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facility College Ground",
                "verbose_name_plural": "Facility College Grounds",
                "db_table": "resources_facility_college_ground",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="FacilityHall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("sub_title", models.CharField(blank=True, max_length=250, null=True)),
                ("description", models.TextField()),
                ("date", models.DateField(default=datetime.date.today)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Facility Hall",
                "verbose_name_plural": "Facility Halls",
                "db_table": "resources_facility_hall",
                "ordering": ("-date",),
            },
        ),
        migrations.CreateModel(
            name="FacilityHallTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "highlight_title",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "Facility Hall Title",
                "verbose_name_plural": "Facility Hall Titles",
                "db_table": "resources_facility_hall_title",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="FacilityHotelService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                (
                    "highlight_title",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("description", models.TextField()),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="resources/facility/hotel_service/image/",
                        verbose_name="Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facility Hotel Service",
                "verbose_name_plural": "Facility Hotel Services",
                "db_table": "resources_facility_hotel_service",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="FacilityInternship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField()),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Facility Internship",
                "verbose_name_plural": "Facility Internships",
                "db_table": "resources_facility_internship",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="FacilityLabTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "highlight_title",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "Facility Lab Title",
                "verbose_name_plural": "Facility Lab Titles",
                "db_table": "resources_facility_lab_title",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="FacilityLibrary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                (
                    "highlight_title",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("sub_title", models.CharField(blank=True, max_length=150, null=True)),
                ("description", models.TextField()),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="resources/facility/library/image/",
                        verbose_name="Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facility Library",
                "verbose_name_plural": "Facility Libraries",
                "db_table": "resources_facility_library",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="GalleryEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("date", models.DateField(default=datetime.date.today)),
                (
                    "video",
                    models.FileField(
                        default="resources/Galleries/events/videos/video.mp4",
                        upload_to="resources/Galleries/events/videos/",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Gallery Event",
                "verbose_name_plural": "Gallery Events",
                "db_table": "resources_gallery_event",
                "ordering": ("-date",),
            },
        ),
        migrations.CreateModel(
            name="GallerySpotlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("sub_title", models.CharField(max_length=220)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="resources/Galleries/spotlight/image/",
                        verbose_name="Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gallery Spotlight",
                "verbose_name_plural": "Gallery Spotlights",
                "db_table": "resources_gallery_spotlight",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="GalleryEventAlbum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="resources/Galleries/events/images/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="resources.galleryevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gallery Event Album",
                "verbose_name_plural": "Gallery Event Albums",
                "db_table": "resources_gallery_event_album",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="FacilityLab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("sub_title", models.CharField(blank=True, max_length=150, null=True)),
                ("description", models.TextField()),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="resources/facility/lab/images/", verbose_name="Image"
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labs",
                        to="resources.facilitylabtitle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facility Lab",
                "verbose_name_plural": "Facility Labs",
                "db_table": "resources_facility_lab",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="FacilityInternshipGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="resources/facility/internship/images/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "internship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="resources.facilityinternship",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facility Internship Gallery",
                "verbose_name_plural": "Facility Internship Galleries",
                "db_table": "resources_facility_internship_gallery",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="FacilityHallGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="resources/facility/hall/images/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="resources.facilityhall",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facility Hall Gallery",
                "verbose_name_plural": "Facility Hall Galleries",
                "db_table": "resources_facility_hall_gallery",
                "ordering": ("-id",),
            },
        ),
        migrations.AddField(
            model_name="facilityhall",
            name="hall",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="halls",
                to="resources.facilityhalltitle",
            ),
        ),
        migrations.CreateModel(
            name="FacilityAdministrativeGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="resources/facility/administrative/images/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "administrative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="resources.facilityadministrative",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facility Administrative Gallery",
                "verbose_name_plural": "Facility Administrative Galleries",
                "db_table": "resources_facility_administrative_gallery",
                "ordering": ("-id",),
            },
        ),
    ]
